ActionManager {
 Actions {
  Action IBX_InventoryCrateTransfer {
   InputSource InputSourceSum "{A1E6470C8DBF3901}" {
    Sources {
     InputSourceValue "{A1E6470C8DBF3902}" {
      FilterPreset "hold"
      Input "keyboard:KC_G"
      Filter InputFilterHoldOnce "{A1E6470C8DBF3903}" {
       HoldDuration 5000
      }
     }
     InputSourceValue "{A1E6470C8DBF3904}" {
      FilterPreset "gamepad:hold"
      Input "gamepad0:y"
      Filter InputFilterHoldOnce "{A1E6470C8DBF3905}" {
       HoldDuration 5000
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext InventoryMenuContext {
   ActionRefs +{
    "IBX_InventoryCrateTransfer"
   }
  }
 }
}
