SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories +{
  SCR_KeyBindingCategory "{A1E6470C8DBF3920}" {
   m_sName "Inventory Boxes"
   m_sDisplayName "Inventory Boxes"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{A1E6470C8DBF3921}" {
     m_sActionName "separator"
     m_sDisplayName "Inventory Boxes"
    }
    SCR_KeyBindingEntry "{A1E6470C8DBF3922}" {
     m_sActionName "IBX_InventoryCrateTransfer"
     m_sDisplayName "Load / Unload Crate"
     m_sPreset "hold"
    }
   }
  }
 }
}
