MenuManager {
 MenuPresets {
  MenuPreset NIRE_Notepad {
   Layout "{1491238DE559429D}UI/layouts/NiRe_Notepad/NIRE_Notepad.layout"
   ActionContext "MenuContext"
   Class "NIRE_NotepadMenu"
  }
  MenuPreset NIRE_LogisticsMenu {
   Layout "{8D02B4399E3F2AD0}UI/layouts/NiRe_Notepad/NIRE_LogisticsScreen.layout"
   ActionContext "MenuContext"
   Class "NIRE_LogisticsScreenMenu"
  }
 }
}
