ActionManager {
 Actions {
  Action NIRE_ToggleNotepad {
   InputSource InputSourceSum "{7BC5E61450D4446A}" {
    Sources {
     InputSourceValue "{1599900E7D83495A}" {
      FilterPreset "click"
      Input "keyboard:KC_F6"
      Filter InputFilterClick "{5CE686E1A5FF4335}" {
      }
     }
    }
   }
  }
  Action NIRE_CloseNotepad {
   InputSource InputSourceValue "{DDD0BF17D16C4822}" {
    Input "keyboard:KC_ESCAPE"
   }
  }
  Action NIRE_EditorPointer {
   InputSource InputSourceValue "{7A16000000000001}" {
    Input "mouse:button0"
    Filter InputFilterDown "{7A16000000000002}" {
    }
   }
  }
 }
 Contexts {
  ActionContext IngameContext {
   ActionRefs +{
    "NIRE_ToggleNotepad"
   "NIRE_CloseNotepad"
    "NIRE_EditorPointer"
   }
  }
  ActionContext MapContext {
   ActionRefs +{
    "NIRE_ToggleNotepad"
   "NIRE_CloseNotepad"
    "NIRE_EditorPointer"
   }
  }
  ActionContext MenuTextEditContext {
   ActionRefs +{
    "NIRE_ToggleNotepad"
    "NIRE_CloseNotepad"
    "NIRE_EditorPointer"
   }
  }
  ActionContext VONContext {
   Priority 1100
  }
 }
}
