SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories +{
  SCR_KeyBindingCategory "{B32A207551EB413A}" {
   m_sName "NiRe Notepad"
   m_sDisplayName "#NIRE-KeyBinding_Category"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{92EE356404114FAE}" {
     m_sActionName "separator"
     m_sDisplayName "#NIRE-KeyBinding_Category"
    }
    SCR_KeyBindingEntry "{A8E2501198974C34}" {
     m_sActionName "NIRE_ToggleNotepad"
     m_sDisplayName "#NIRE-KeyBinding_Toggle"
     m_sPreset "click"
    }
   }
  }
 }
}
