SCR_NavigationBarConfig {
 m_aEntries +{
  NavigationButtonEntry "{A1E6470C8DBF3910}" {
   m_sDisplayName "LOAD / UNLOAD CRATE"
   m_sAction "IBX_InventoryCrateTransfer"
   m_sButtonID "ButtonIBXCrateTransfer"
  }
 }
}
