SCR_ConfigurableDialogUiPresets {
 m_aPresets {
  SCR_ConfigurableDialogUiPreset "{68D9322F10C6EB63}" {
   m_sLayout "{480CFD7B3504A35A}UI/layouts/Menus/Dialogs/ConfigurableDialog_Big_Quiz 2.layout"
   m_sTag "srq_quiz"
   m_eVisualStyle MESSAGE
   m_bShowIcon 0
   m_sMessage ""
   m_sTitle ""
  }
 }
}