SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
   SCR_EntityCatalogInventoryItem "{5C62F7D8F7F788DD}" {
    m_sEntityPrefab "{A2CEF84144FB299B}Prefabs/Items/Medicine/SalineBag_01/SalineBag_US_500.et"
   }
    SCR_EntityCatalogInventoryItem "{6A2F4EEF77ADEB2A}" {
     m_sEntityPrefab "{02C5C61EB9FE39D3}Prefabs/Items/Medicine/SalineBag_01/SalineBag_US_250.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{70F37AD193795F11}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2F4EEF75B4580D}" {
     m_sEntityPrefab "{D434DDDBD0DAC334}Prefabs/Items/Medicine/SalineBag_01/SalineBag_US_1250.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{70F37AD193795F12}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A052878115236AB}" {
     m_sEntityPrefab "{02C5C61EB9FE39D2}Prefabs/Items/Medicine/SalineBag_01/SalineBag_US_1000.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A05287E9E3E812C}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A05287810E7DEFC}" {
     m_sEntityPrefab "{743FE3842DDFD37D}Prefabs/Items/Medicine/SalineBag_01/SalineBag_US_1500.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A05287EB4B433AF}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
      }
     }
    }
   }
  }
 }
}
