SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{A1E6470C8DBF3970}" {
   m_Info SCR_UIInfo "{A1E6470C8DBF3971}" {
    Name "Inventory Boxes"
    Description "Finite inventory crates"
   }
   m_LabelType IBX_INVENTORY_BOXES
   m_LabelGroupType ENTITYTYPE
  }
 }
}
