SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F7414CA4A}" {
   m_aEntities {
   SCR_EntityCatalogInventoryItem "{5C62F7DF30AA69BA}" {
    m_sEntityPrefab "{883BA62332B2278B}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_500.et"
   }
    SCR_EntityCatalogInventoryItem "{6A2F4EEE879B9190}" {
     m_sEntityPrefab "{2830987CCFB737C3}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_250.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{70F37AD193795F21}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A2F4EEE86C189D5}" {
     m_sEntityPrefab "{FA97410FF7466C72}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_1250.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{70F37AD193795F22}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A0528783EE25C21}" {
     m_sEntityPrefab "{2830987CCFB737C2}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_1000.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A05287EA29D7BB7}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A0528783C1E45C5}" {
     m_sEntityPrefab "{5A9C7F500A437C3B}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_1500.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A05287EA9AAE65B}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
      }
     }
    }
   }
  }
 }
}
