ActionManager {
 Actions {
  Action RAMI_ToggleMedicalMenu {
   InputSource InputSourceSum "{2D61AF5ACFDD4411}" {
    Sources {
     InputSourceValue "{BFED62D7BB674BB1}" {
      FilterPreset "click"
      Input "keyboard:KC_H"
      Filter InputFilterClick "{8C7A4F1B2D6E9031}" {
      }
     }
     InputSourceCombo "{C61BA90257264041}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{61053B427627463C}" {
        Input "gamepad0:shoulder_right"
       }
       InputSourceValue "{A367FE736F6641FB}" {
        Input "gamepad0:pad_right"
        Filter InputFilterClick "{8C7A4F1B2D6E9032}" {
        }
       }
      }
     }
    }
   }
  }
  Action RAMI_MedicalMenuModifier {
   InputSource InputSourceValue "{D28A40D1A7264A03}" {
    Input "gamepad0:shoulder_right"
   }
  }
  Action RAMI_CloseMedicalMenu {
   InputSource InputSourceSum "{A91B2C3D4E5F6071}" {
    Sources {
     InputSourceValue "{A91B2C3D4E5F6072}" {
      Input "keyboard:KC_ESCAPE"
     }
     InputSourceValue "{F379756E0F1D4163}" {
      Input "gamepad0:b"
     }
    }
   }
  }
  Action RAMI_PreviousMedicalPage {
   InputSource InputSourceValue "{D28A40D1A7264A01}" {
    Input "gamepad0:left_trigger"
   }
  }
  Action RAMI_NextMedicalPage {
   InputSource InputSourceValue "{D28A40D1A7264A02}" {
    Input "gamepad0:right_trigger"
   }
  }
 }
 Contexts {
  ActionContext IngameContext {
   ActionRefs +{
    "RAMI_ToggleMedicalMenu"
    "RAMI_MedicalMenuModifier"
   }
  }
 }
}
