SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{9755517148A745DE}" {
   m_sName "Advanced Medical Interface"
   m_sDisplayName "Advanced Medical Interface"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{276D11FB134E4E4B}" {
     m_sActionName "separator"
     m_sDisplayName "Advanced Medical Interface"
    }
    SCR_KeyBindingEntry "{3F504F0DE35B4B92}" {
     m_sActionName "RAMI_ToggleMedicalMenu"
     m_sDisplayName "Open Medical Interface"
     m_sPreset "click"
    }
   }
  }
 }
}
