MenuManager {
 MenuPresets {
  MenuPreset LM_LogisticsTerminal {
   Layout "{E8F4BF04A7E8E65A}UI/layouts/LM_LogisticsTerminal.layout"
   ActionContext "MenuContext"
   Class "LM_LogisticsTerminalUI"
  }
 }
}
