ActionManager {
 Actions {
  Action LM_ToggleLogisticsMaster {
   InputSource InputSourceSum "{A1E6470C8DBF3971}" {
    Sources {
     InputSourceValue "{A1E6470C8DBF3972}" {
      FilterPreset "select"
      Input "keyboard:KC_F6"
     }
    }
   }
  }
  Action LM_CloseLogisticsMaster {
   InputSource InputSourceSum "{A1E6470C8DBF3973}" {
    Sources {
     InputSourceValue "{A1E6470C8DBF3974}" {
      Input "keyboard:KC_ESCAPE"
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "LM_ToggleLogisticsMaster"
   }
  }
  ActionContext EditorContext {
   ActionRefs +{
    "LM_ToggleLogisticsMaster"
   }
  }
  ActionContext InGameMenuContext {
   ActionRefs +{
    "LM_ToggleLogisticsMaster"
   }
  }
  ActionContext MenuContext {
   ActionRefs +{
    "LM_ToggleLogisticsMaster"
   }
  }
 }
}