SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories +{
  SCR_KeyBindingCategory "{A1E6470C8DBF3980}" {
   m_sName "LogisticMaster"
   m_sDisplayName "LogisticMaster"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{A1E6470C8DBF3981}" {
     m_sActionName "separator"
     m_sDisplayName "LogisticMaster"
    }
    SCR_KeyBindingEntry "{A1E6470C8DBF3982}" {
     m_sActionName "LM_ToggleLogisticsMaster"
     m_sDisplayName "LogisticMaster öffnen"
     m_sPreset "select"
    }
   }
  }
 }
}
